version: 2.1
jobs:

  build_international_instance:
    working_directory: ~/PssDhisCustomApp/InternationalInstance
    docker:
      - image: cimg/openjdk:17.0.1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - setup_remote_docker
      - checkout:
          path: ~/PssDhisCustomApp
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Build with Maven
                command: mvn install
            - run:
                name: Build Docker Image and Push to Docker Hub
                command: |
                  docker build -t dnjau/dhis_pss:v3 .
                  echo "Sc281-6736/2014" | docker login -u "dnjau" --password-stdin
                  docker push dnjau/dhis_pss:v3
                  docker logout


workflows:
  version: 2
  build_and_push:
    jobs:
      - build_international_instance







