version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5438:5432'
    container_name: national_db
    volumes:
      - national_db:/var/lib/postgresql/data/national_db
      - file_db:/var/lib/postgresql/data/file_db

volumes:
  national_db:
    driver: local
  file_db:
    driver: local

# docker-compose -f docker-compose-postgres.yaml up