name: Build and Deploy Spring Boot Microservices

on:
  push:
    branches:
      - development

env:
  DOCKER_USERNAME: dnjau
  DOCKER_PASSWORD: Sc281-6736/2014

  SSH_KEY_1: Sc281-6736/2014
  SSH_HOST_1: 172.104.91.116
  SSH_USER_1: dnjau
  CONTAINER_NAME_INTERNATIONAL: dhis_pss_international

#  SSH_KEY_2: ${{ secrets.SSH_KEY_2 }}
#  SSH_HOST_2: 172.104.91.99
#  SSH_USER_2: dnjau
#  CONTAINER_NAME_NATIONAL: dhis_pss_national

jobs:
  build_microservice_1:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: openjdk
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build International Instance
      run: |
        cd InternationalInstance
        mvn clean install

    - name: Build Docker image for Microservice 1
      uses: docker/build-push-action@v2
      with:
        context: microservice_1
        push: true
        tags: dnjau/dhis_pss_international:v1
      env:
        DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}


  deploy_microservice_1:
    runs-on: ubuntu-20.04
    needs: build_microservice_1

    steps:
    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST_1 }}
        username: ${{ env.SSH_USER_1 }}
        key: ${{ env.SSH_KEY_1 }}
        script: |
          docker stop ${{ env.CONTAINER_NAME_INTERNATIONAL }}
          docker pull dnjau/dhis_pss_international:v1
          docker run -d --name ${{ env.CONTAINER_NAME_INTERNATIONAL }} -p 7007:7007 dnjau/dhis_pss_international:v1
          docker logout

