name: Build and Deploy Spring Boot Microservices

on:
  push:
    branches:
      - development

env:
  DOCKER_USERNAME: dnjau
  DOCKER_PASSWORD: Sc281-6736/2014

  SSH_PASS: Sc281-6736/2014
  SSH_HOST_1: 172.104.91.116
  SSH_USER: dnjau
  CONTAINER_NAME_INTERNATIONAL: dhis_pss_international
  IMAGE_NAME_INTERNATIONAL: dnjau/dhis_pss_international:v1

#  SSH_KEY_2: ${{ secrets.SSH_KEY_2 }}
#  SSH_HOST_2: 172.104.91.99
#  SSH_USER_2: dnjau
#  CONTAINER_NAME_NATIONAL: dhis_pss_national

jobs:
  build_microservice_international:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build International Instance
      run: |
        cd InternationalInstance
        mvn clean install

    - name: Build & push International Docker image
      run: |
        cd InternationalInstance
        docker buildx build -t ${{ env.IMAGE_NAME_INTERNATIONAL }} .
        docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
        docker push ${{ env.IMAGE_NAME_INTERNATIONAL }}
        docker logout


  deploy_microservice_international:
    runs-on: ubuntu-20.04
    needs: build_microservice_international

    steps:
    - name: SSH into server and update container
      run: |
        sshpass -p ${{ env.SSH_PASS }} ssh -o StrictHostKeyChecking=no -l ${{ env.SSH_USER }} ${{ env.SSH_HOST_1 }}
        if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_INTERNATIONAL }}; then
          docker stop ${{ env.CONTAINER_NAME_INTERNATIONAL }}
          docker rm ${{ env.CONTAINER_NAME_INTERNATIONAL }}
        fi
        docker pull ${{ env.IMAGE_NAME_INTERNATIONAL }}
        docker run -d --name ${{ env.CONTAINER_NAME_INTERNATIONAL }} -p 7007:7007 ${{ env.IMAGE_NAME_INTERNATIONAL }}
        while [ "$(docker inspect -f '{{.State.Running}}' ${{ env.CONTAINER_NAME_INTERNATIONAL }})" != "true" ]; do
          sleep 1;
        done;
        docker logout
        exit

